In [1]:
import numpy as np

In [2]:
score=np.loadtxt("python_score.csv", delimiter=',', dtype='float64')

In [3]:
dset=score[:,:10].T
dset

array([[ 3.,  4.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  2.,  2.,  1.,  2.,  2.,  2.,  9.,  5.],
       [ 3.,  4.,  1.,  1.,  2.,  4.,  1.,  4.,  4.,  2.,  3.,  3.,  3.,
         2.,  2.,  2.,  1.,  2.,  2.,  1.,  4.,  7.],
       [ 4.,  4.,  1.,  1.,  3.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  4.,  2.,  1.,  2.,  4.,  2., 10.,  8.],
       [ 3.,  4.,  1.,  1.,  2.,  4.,  1.,  4.,  4.,  2.,  4.,  2.,  3.,
         3.,  2.,  1.,  1.,  2.,  2.,  4.,  9.,  5.],
       [ 3.,  4.,  1.,  1.,  4.,  2.,  1.,  4.,  4.,  2.,  2.,  3.,  3.,
         3.,  2.,  1.,  1.,  2.,  2.,  4.,  6.,  7.],
       [ 3.,  3.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  2.,  2.,  1.,  2.,  2.,  2.,  8.,  8.],
       [ 3.,  4.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         1.,  2.,  2.,  1.,  2.,  2.,  3., 10.,  6.],
       [ 3.,  4.,  1.,  1.,  4.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
         3.,  2.,  2.,  1.,  2.,  2., 

In [4]:
answer=score[:22,10]
answer

array([ 3.,  4.,  1.,  1.,  2.,  2.,  1.,  4.,  4.,  2.,  4.,  3.,  3.,
        3.,  2.,  2.,  1.,  2.,  2.,  2., 10., 10.])

In [5]:
bool_answer=(answer==dset)
bool_answer

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True, False,  True,  True,  True,  True,
         True, False, False, False],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True, False, False, False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True, False, False, False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True

In [6]:
bool_answer=bool_answer.dot(1)
bool_answer

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1]])

In [7]:
bool_answer[:,20:]=dset[:,20:]
bool_answer

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  9,  5],
       [ 1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  0,  1,  1,  0,  1,  1,
         1,  1,  1,  0,  4,  7],
       [ 0,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,
         1,  1,  0,  1, 10,  8],
       [ 1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,
         1,  1,  1,  0,  9,  5],
       [ 1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  0,
         1,  1,  1,  0,  6,  7],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  8,  8],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,
         1,  1,  1,  0, 10,  6],
       [ 1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  7,  8],
       [ 1,  0,  1,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         0,  0,  1,  0,  6,  9],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,

In [8]:
scoreset=bool_answer
scoreset

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  9,  5],
       [ 1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  0,  1,  1,  0,  1,  1,
         1,  1,  1,  0,  4,  7],
       [ 0,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,
         1,  1,  0,  1, 10,  8],
       [ 1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,
         1,  1,  1,  0,  9,  5],
       [ 1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  0,
         1,  1,  1,  0,  6,  7],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  8,  8],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,
         1,  1,  1,  0, 10,  6],
       [ 1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  7,  8],
       [ 1,  0,  1,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         0,  0,  1,  0,  6,  9],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,

In [9]:
points=[4 for i in range(20)]
points.append(1)
points.append(1)
points

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1]

In [10]:
np.dot(scoreset,points)

array([94, 75, 82, 78, 77, 92, 88, 91, 67, 87])